name: Continuous Integration
on: push
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - name: Lint
        uses: astral-sh/ruff-action@v4.1.0
        with:
          args: check
      - name: Install mercury_rfs
        run: pip install .[test]
      - name: Run Pytest
        run: pytest